# Generated by Django 5.2.17 on 2026-09-22 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(help_text="Edição do ENEM, ex.: 2025")),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("LC", "Linguagens e Códigos"),
                            ("CH", "Ciências Humanas"),
                            ("CN", "Ciências da Natureza"),
                            ("MT", "Matemática"),
                        ],
                        max_length=2,
                    ),
                ),
                ("nota_tri", models.DecimalField(decimal_places=1, max_digits=6)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="avaliacoes.aluno",
                    ),
                ),
            ],
        ),
    ]
